import Head from 'next/head';
import HomeComp from '../components/HomeComp';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Nexty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeComp />

    </div>
  )
}